--경기도에 위치한 식품창고 목록 출력하기
SELECT 
WAREHOUSE_ID,
WAREHOUSE_NAME,
ADDRESS,
IFNULL(FREEZER_YN,'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE 
WHERE WAREHOUSE_NAME LIKE '%경기%'

--이름 없는 동물의 아이디
SELECT 
ANIMAL_ID 
FROM ANIMAL_INS
WHERE NAME IS NULL 
ORDER BY ANIMAL_ID

--이름 있는 동물의 아이디
SELECT ANIMAL_ID 
FROM ANIMAL_INS 
WHERE NAME IS NOT NULL 
ORDER BY ANIMAL_ID

--NULL 처리하기
SELECT 
ANIMAL_TYPE,
IFNULL(NAME,'No name') AS NAME ,
SEX_UPON_INTAKE
FROM ANIMAL_INS

--나이 정보가 없는 회원 수 구하기
SELECT COUNT(*) AS USERS
FROM USER_INFO 
WHERE AGE IS NULL

--ROOT 아이템 구하기
SELECT T.ITEM_ID , I.ITEM_NAME
FROM ITEM_TREE T JOIN ITEM_INFO I
USING(ITEM_ID)
WHERE T.PARENT_ITEM_ID IS NULL 

--잡은 물고기의 평균 길이 구하기
SELECT ROUND(AVG(IFNULL(LENGTH,10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO 

--업그레이드 할 수 없는 아이템 구매하기
WITH ULTIMATE AS(
    SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL  ) 
)

SELECT U.ITEM_ID,	I.ITEM_NAME,	I.RARITY
FROM ULTIMATE U JOIN ITEM_INFO I
USING(ITEM_ID)
ORDER BY 1 DESC