--조건에 맞는 도서와 저자 리스트 출력하기
SELECT B.BOOK_ID , A.AUTHOR_NAME , DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B JOIN AUTHOR A
USING(AUTHOR_ID)
WHERE B.CATEGORY = "경제"
ORDER BY 3

--상품 별 오프라인 매출 구하기
SELECT P.PRODUCT_CODE , SUM(OS.SALES_AMOUNT*P.PRICE) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE OS
USING(PRODUCT_ID)
GROUP BY OS.PRODUCT_ID
ORDER BY 2 DESC , 1

--오랜 기간 보호한 동물(1)
WITH ANIMAL_ID AS (
    SELECT ANIMAL_ID 
    FROM ANIMAL_OUTS
)

SELECT NAME , DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT * FROM ANIMAL_ID)
ORDER BY DATETIME 
LIMIT 3

--없어진 기록 찾기
SELECT AO.ANIMAL_ID , AO.NAME
FROM ANIMAL_OUTS AO LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL

--있었는데요 없었습니다.
SELECT AI.ANIMAL_ID , AI.NAME
FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO
USING(ANIMAL_ID)
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME