--평균 일일 대여 요금 구하기
SELECT ROUND(AVG(DAILY_FEE)) AS AVERAGE_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = 'SUV'

--재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID , PRODUCT_ID
FROM ONLINE_SALE
GROUP BY 1,2
HAVING COUNT(*) > 1
ORDER BY 1,2 DESC

--역순 정렬하기
SELECT NAME,DATETIME 
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC

--아픈 동물 찾기
SELECT ANIMAL_ID,NAME 
FROM ANIMAL_INS 
WHERE INTAKE_CONDITION='SICK'

--어린동물찾기
SELECT ANIMAL_ID , NAME 
FROM ANIMAL_INS 
WHERE INTAKE_CONDITION <>'Aged'

--동물의 아이디와 이름
SELECT ANIMAL_ID , NAME 
FROM ANIMAL_INS 
ORDER BY ANIMAL_ID

--여러 기준으로 정렬하기
SELECT ANIMAL_ID , NAME, DATETIME 
FROM ANIMAL_INS  
ORDER BY NAME ,DATETIME DESC

--상위 N개 레코드
SELECT NAME 
FROM (
    SELECT * 
    FROM ANIMAL_INS 
    ORDER BY DATETIME
) 
WHERE ROWNUM =1

--조건에 맞는 회원수 구하기
SELECT COUNT(*) AS USERS
FROM USER_INFO
WHERE JOINED LIKE '2021%'
AND AGE BETWEEN 20 AND 29

--흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME,DR_ID,MCDP_CD,DATE_FORMAT(HIRE_YMD,'%Y-%m-%d')
FROM DOCTOR
WHERE MCDP_CD = 'CS' 
OR MCDP_CD = 'GS'
ORDER BY 4 DESC , 1 ASC

--과일로 만든 아이스크림 구하기
WITH flavor_fruit AS(
SELECT FLAVOR
FROM ICECREAM_INFO 
WHERE INGREDIENT_TYPE ='fruit_based'
)

SELECT H.FLAVOR
FROM FIRST_HALF H JOIN flavor_fruit F
USING(FLAVOR)
WHERE H.TOTAL_ORDER >= 3000

--3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID,	MEMBER_NAME,	GENDER	,DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE GENDER = 'W'
AND TLNO IS NOT NULL
AND MONTH(DATE_OF_BIRTH) ='3'
ORDER BY 1

--서울에 위치한 식당 목록 출력하기
SELECT REST_ID , REST_NAME ,FOOD_TYPE , FAVORITES,ADDRESS , ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO I JOIN REST_REVIEW R
USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY 6 DESC , 4 DESC

--조건에 부합하는 중고거래 댓글 조회하기
SELECT 
B.TITLE , 
B.BOARD_ID , 
REPLY_ID ,
U.WRITER_ID ,
U.CONTENTS,
DATE_FORMAT(U.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY U
USING(BOARD_ID)
WHERE B.CREATED_DATE LIKE "2022-10%"
ORDER BY 6 , 1

--인기있는 아이스크림
SELECT FLAVOR
FROM FIRST_HALF 
ORDER BY TOTAL_ORDER DESC , SHIPMENT_ID

--강원도에 위치한 생산공장 목록 출력하기
SELECT 
FACTORY_ID,	
FACTORY_NAME,	
ADDRESS
FROM FOOD_FACTORY 
WHERE ADDRESS LIKE '강원도%'
ORDER BY  1

--12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME,
PT_NO,
GEND_CD,
AGE,
IFNULL(TLNO,'NONE') AS TLNO
FROM PATIENT 
WHERE GEND_CD = 'W'
AND AGE <= 12
ORDER BY 4 DESC , 1

--조건에 맞는 도서 리스트 출력하기
SELECT BOOK_ID,
DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY ='인문'
AND PUBLISHED_DATE LIKE '2021%'
ORDER BY 2

--Python 개발자 찾기
SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME
FROM DEVELOPER_INFOS 
WHERE SKILL_1 = 'Python'
OR SKILL_2 ='Python'
OR SKILL_3 ='Python'
ORDER BY 1
